### ISSUE TITLE
Use not SSR friendly dependencies

### ISSUE THREAD

**Issue by anthonyvialleton** [WebbyLab/itsquiz-wall#179] opened 2016-11-07 10:26 UTC
In the first place thanks for sharing your knowledges about React in real world situation, it's highly appreciated.

I would like to know how to integrate a client side dependency that is using Window, Navigator (Openlayers 3 and Highcharts for example).
I just need to bypass the SSR of this client only dependencies and execute all this code in browser only.

Is it easy to implement this specific behavior there ?

I tried inject directly from the `componentDidMount` handler as this : 

```
 componentDidMount() {
        const ol = require('openlayers');

        ol.Map({
            target: 'map',
            layers: [
                new ol.layer.Tile({
                    source: new ol.source.OSM()
                })
            ],
            view: new ol.View({
                center: [0, 0],
                zoom: 2
            })
        });

        this.forceUpdate();
    }
```

And also add this line to my component render : 

` <div id="map" className="map"/>`
 
But I got this error : 

```
TypeError: Cannot read property 'bind' of undefined
    at Object.H [as Map] (eval at <anonymous> 
```

**Comment by koorchik** [comment] 2016-11-07 18:03
Usually, all client dependencies can be imported on a server, as they are just pure JS. Of course, they can depend on browser specific features but if you do not make calls to the library on the server side - it should work. Moreover, you can do dynamic require as you do. 
In this case, I guess the error is not related to isomorphic nature of the app. It is just some error in library usage.

**Comment by koorchik** [comment] 2016-11-07 20:26
I'll close the issue. Feel free to reopen if the issue is really related to the isomorphic nature of the app.

**Closed by koorchik** 2016-11-07 20:26 UTC
